/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ims.ui.report;

import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.servlet.ServletOutputStream;
import javax.sql.DataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
/**
 *
 * @author inreyes
 */
public class MyiReportViewer extends javax.swing.JInternalFrame {

    /**
     * Creates new form MyiReportViewer
     */
    private DataSource dataSource;

    public DataSource getDataSource() {
        return dataSource;
    }

    public void setDataSource(DataSource dataSource) {
        this.dataSource = dataSource;
    }
    
    String urlDB = "jdbc:oracle:thin:@172.16.7.9:1521:bcr";
    String user = "mgrssi";
    public MyiReportViewer() {
        super("Report Viewer", true, true, true, true);
        initComponents();
        setBounds(10, 10, 600, 500);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public MyiReportViewer(String fileName){
        this(fileName, null);
    }
    public MyiReportViewer(String fileName, HashMap parameter) {
        this();
        try {
            //Class.forName("oracle.jdbc.driver.OracleDriver");
            //urlDB = "jdbc:oracle:thin:@localhost:1521:xe";
            //Connection con = DriverManager.getConnection(urlDB, user, "snorkels");
            Connection con = dataSource.getConnection();
        System.out.println("Ya me connecté..");
        if (parameter == null){
                parameter = new HashMap<String, Object>();
        }
        System.out.println("Trying to print " + fileName);
        JasperPrint print = JasperFillManager.fillReport(fileName, parameter, con);
        System.out.println("print..");
            JRViewer viewer = new JRViewer(print);
            Container c = getContentPane();
            c.add(viewer);
            
        } //catch(ClassNotFoundException cnfe)
        //{
            //cnfe.printStackTrace();
        //}
        catch(SQLException sqle) {
            sqle.printStackTrace();
        }
        catch(JRException jre) {
            jre.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
